### ISSUE TITLE
A requirements.txt file would be nice.

### ISSUE THREAD

**Issue by pranavchat14** [faustomorales/vit-keras#10]
I was facing an error in loading the model. Resolved by downgrading Tensorflow version to 2.1.0.
Upgrading this repo to latest version of Tensorflow would simply things a little more.
Thanks for the implementation.

**Comment by faustomorales** [comment]
Yes, the intention is for this package to work with the latest available version of TensorFlow. Could you provide the following?

- The version of TensorFlow that didn't work
- The error (along with a full traceback)

The dependencies for this package are specified using [pyproject.toml](https://github.com/faustomorales/vit-keras/blob/df804ae2e9aaf14008433ecc8cfa2ed8074776ca/pyproject.toml#L28), which would make a `requirements.txt` superfluous. TensorFlow is not specified there in order to allow people to install their preferred flavor of the package (e.g., some people still use `tensorflow-gpu` or build from source).

**Comment by pranavchat14** [comment]
I am using Google Colab. I am doing exactly like instructed in README.md. 

I have installed ViT using pip. Then I go with this example:

image_size = 224
model = vit.vit_l32(
    image_size=image_size,
    activation='sigmoid',
    pretrained=True,
    include_top=True,
    pretrained_top=False,
    classes=200
)

The details are as follows:

-  The version of TensorFlow that didn't work: tensorflow==2.4.1

- The error message: Below

---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-3-ef0c9bb529a3> in <module>()
      8     include_top=True,
      9     pretrained_top=False,
---> 10     classes=200
     11 )

14 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     55     RuntimeError: when unable to load the library or get the python wrappers.
     56   """
---> 57   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     58   try:
     59     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_addons/custom_ops/activations/_activation_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE

**Comment by faustomorales** [comment]
Ah, you've run into a compatibility problem between `tensorflow_addons` and `tensorflow`. Unfortunately, users have to manage the version compatibility for these two packages manually. See [the `tensorflow_addons` README](https://github.com/tensorflow/addons#c-custom-op-compatibility) for more information on why that's the case. Unfortunately, it's not something that `vit-keras` can handle automatically.

Because Google Colab periodically updates the version of TensorFlow that ships, it's also not easy to just set a version of `tensorflow_addons` to fix it. For that reason, I suggest setting a fixed version for *both* `tensorflow` and `tensorflow_addons` at the top of your notebook.

As an example, if you want to use `tensorflow==2.4.1`, you can look it up on the `tensorflow_addons` [compatibility chart](https://github.com/tensorflow/addons#c-custom-op-compatibility-matrix) and see that it requires `tensorflow_addons==0.12.1`. And so the following would work in a Google Colab notebook.

```python
!pip install -q vit-keras tensorflow==2.4.1 tensorflow_addons==0.12.1

import vit_keras.vit as vit

image_size = 224
model = vit.vit_l32(
  image_size=image_size,
  activation='sigmoid',
  pretrained=True,
  include_top=True,
  pretrained_top=False,
  classes=200
)
```

Closing this for now but let me know if this doesn't solve your problem.
