### ISSUE TITLE
Gelu Warning

### ISSUE THREAD

**Issue by awsaf49** [faustomorales/vit-keras#14]
While trying to load the model I'm getting this `Userwarning`, 
```
/opt/conda/lib/python3.7/site-packages/tensorflow_addons/activations/gelu.py:81: UserWarning: Default value of `approximate` is changed from `True` to `False`   
"Default value of `approximate` is changed from `True` to `False`
```
Is this expected or we can just avoid it.. ?

**Comment by faustomorales** [comment]
Ah, yeah, it's a harmless warning but I've fixed it in ed267c496b0d82d1ddf73d8848b87c908419e092 which is now published on PyPi as v0.0.13. The warning was indicating that the default `gelu` behavior was changed to disable approximation (i.e., in order to make the activation computation a little faster).
