### ISSUE TITLE
Difference Between all the VIT models 

### ISSUE THREAD

**Issue by king398** [faustomorales/vit-keras#9]
Could You please Explain me what is the difference Between all the VIT models like  VIT b16 vs l16 and VIT l16 vs VIT l32. Any help would he appreciated. Thank you

**Comment by faustomorales** [comment]
The letters refer to each of the three sizes for the network (*B*ase, *L*arge, *H*uge). Please see Table 2 of [the paper](https://arxiv.org/pdf/2010.11929.pdf) for a description of each of the three sizes. The number refers to the patch size for the transformer. Please see the paper (particularly the introduction and Figure 1) for more information on how the patches are used.

**Comment by Sicily-F** [comment]
Hi there, I know this issue is closed, but I have a related question. I've been using the b32 version of the model, which I'm guessing is the base version with patch 32. I have scoured the paper and can work out the number of parameters, i.e. 87,467,239, but not the memory size in MB of the model. It states in the paper (https://arxiv.org/pdf/2010.11929.pdf) that vision transformers use less memory than ResNets but can't find the memory size required.
